In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv("../data/college_student_placement_dataset.csv")
df.head()

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,CLG0030,107,6.61,6.28,8,No,8,8,4,No
1,CLG0061,97,5.52,5.37,8,No,7,8,0,No
2,CLG0036,109,5.36,5.83,9,No,3,1,1,No
3,CLG0055,122,5.47,5.75,6,Yes,1,6,1,No
4,CLG0004,96,7.91,7.69,7,No,8,10,2,No

In [6]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   College_ID              10000 non-null  str
 1   IQ                      10000 non-null  int64
 2   Prev_Sem_Result         10000 non-null  float64
 3   CGPA                    10000 non-null  float64
 4   Academic_Performance    10000 non-null  int64
 5   Internship_Experience   10000 non-null  str
 6   Extra_Curricular_Score  10000 non-null  int64
 7   Communication_Skills    10000 non-null  int64
 8   Projects_Completed      10000 non-null  int64
 9   Placement               10000 non-null  str
dtypes: float64(2), int64(5), str(3)
memory usage: 781.4 KB

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Extra_Curricular_Score,Communication_Skills,Projects_Completed
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,99.471800,7.535673,7.532379,5.546400,4.970900,5.561800,2.513400
std,15.053101,1.447519,1.470141,2.873477,3.160103,2.900866,1.715959
min,41.000000,5.000000,4.540000,1.000000,0.000000,1.000000,0.000000
25%,89.000000,6.290000,6.290000,3.000000,2.000000,3.000000,1.000000
50%,99.000000,7.560000,7.550000,6.000000,5.000000,6.000000,3.000000
75%,110.000000,8.790000,8.770000,8.000000,8.000000,8.000000,4.000000
max,158.000000,10.000000,10.460000,10.000000,10.000000,10.000000,5.000000

In [7]:
df.isnull().sum()
df = df.dropna()

In [8]:
df.groupby("College_ID")["CGPA"].mean()

College_ID
CLG0001    7.587890
CLG0002    7.627326
CLG0003    7.596598
CLG0004    7.597363
CLG0005    7.243393
             ...
CLG0096    7.663333
CLG0097    7.556832
CLG0098    7.579714
CLG0099    7.630449
CLG0100    7.315361
Name: CGPA, Length: 100, dtype: float64

In [9]:
print(df.columns)

Index(['College_ID', 'IQ', 'Prev_Sem_Result', 'CGPA', 'Academic_Performance',
       'Internship_Experience', 'Extra_Curricular_Score',
       'Communication_Skills', 'Projects_Completed', 'Placement'],
      dtype='str')

In [10]:
df.groupby("Internship_Experience")["IQ"].mean()

Internship_Experience
No     99.474818
Yes    99.467205
Name: IQ, dtype: float64

In [10]:
['College_ID', 'IQ', 'Prev_Sem_Result', 'CGPA', 'Academic_Performance',
 'Internship_Experience', 'Extra_Curricular_Score',
 'Communication_Skills', 'Projects_Completed', 'Placement']

['College_ID',
 'IQ',
 'Prev_Sem_Result',
 'CGPA',
 'Academic_Performance',
 'Internship_Experience',
 'Extra_Curricular_Score',
 'Communication_Skills',
 'Projects_Completed',
 'Placement']

In [11]:
df.shape

(10000, 10)

In [3]:
%pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.11.2-cp314-cp314-win_amd64.whl.metadata (80 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.4.0-cp314-cp314-win_amd64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Downloading fonttools-4.68.0-cp314-cp314-win_amd64.whl.metadata (142 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.1-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.25 in c:\Users\shrey\Lib\site-packages (from matplotlib) (2.4.2)
Requirement already satisfied: packaging>=20.0 in C:\Users\shrey\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.3)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-13.0.0-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.3-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\shrey\Lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\Users\shrey\Lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.11.2-cp314-cp314-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.5 MB 4.8 MB/s eta 0:00:02
   ------- -------------------------------- 1.8/9.5 MB 4.3 MB/s eta 0:00:02
   ----------- ---------------------------- 2.6/9.5 MB 4.1 MB/s eta 0:00:02
   ------------- -------------------------- 3.1/9.5 MB 4.1 MB/s eta 0:00:02
   ----------------- ---------------------- 4.2/9.5 MB 4.0 MB/s eta 0:00:02
   -------------------- ------------------- 5.0/9.5 MB 4.0 MB/s eta 0:00:02
   ------------------------ --------------- 5.8/9.5 MB 4.0 MB/s eta 0:00:01
   --------------------------- ------------ 6.6/9.5 MB 3.9 MB/s eta 0:00:01
   ------------------------------ --------- 7.3/9.5 MB 4.0 MB/s eta 0:00:01
   ---------------------------------- ----- 8.1/9.5 MB 4.0 MB/s eta 0:00:01
   ------------------------------------- -- 8.9/9.5 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 3.9 MB/s  0:00:02
Downloading contourpy-1.4.0-cp314-cp314-win_amd64.whl (240 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.68.0-cp314-cp314-win_amd64.whl (2.5 MB)
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------- ----------------------- 1.0/2.5 MB 5.1 MB/s eta 0:00:01
   ---------------------------- ----------- 1.8/2.5 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------- 2.5/2.5 MB 4.1 MB/s  0:00:00
Downloading kiwisolver-1.5.1-cp314-cp314-win_amd64.whl (72 kB)
Downloading pillow-13.0.0-cp314-cp314-win_amd64.whl (7.3 MB)
   ---------------------------------------- 0.0/7.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.8/7.3 MB 4.8 MB/s eta 0:00:02
   -------- ------------------------------- 1.6/7.3 MB 4.2 MB/s eta 0:00:02
   ------------ --------------------------- 2.4/7.3 MB 4.1 MB/s eta 0:00:02
   ----------------- ---------------------- 3.1/7.3 MB 3.9 MB/s eta 0:00:02
   --------------------- ------------------ 3.9/7.3 MB 4.0 MB/s eta 0:00:01
   ------------------------- -------------- 4.7/7.3 MB 4.0 MB/s eta 0:00:01
   ------------------------------ --------- 5.5/7.3 MB 4.0 MB/s eta 0:00:01
   ---------------------------------- ----- 6.3/7.3 MB 4.0 MB/s eta 0:00:01
   -------------------------------------- - 7.1/7.3 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 7.3/7.3 MB 3.9 MB/s  0:00:01
Downloading pyparsing-3.3.3-py3-none-any.whl (126 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib

   ---------------------------------------- 0/7 [pyparsing]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----------- ---------------------------- 2/7 [kiwisolver]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ---------------------- ----------------- 4/7 [cycler]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------------- 7/7 [matplotlib]

Successfully installed contourpy-1.4.0 cycler-0.12.1 fonttools-4.68.0 kiwisolver-1.5.1 matplotlib-3.11.2 pillow-13.0.0 pyparsing-3.3.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.isnull().sum()

College_ID                0
IQ                        0
Prev_Sem_Result           0
CGPA                      0
Academic_Performance      0
Internship_Experience     0
Extra_Curricular_Score    0
Communication_Skills      0
Projects_Completed        0
Placement                 0
dtype: int64

In [14]:
df.dtypes

College_ID                    str
IQ                          int64
Prev_Sem_Result           float64
CGPA                      float64
Academic_Performance        int64
Internship_Experience         str
Extra_Curricular_Score      int64
Communication_Skills        int64
Projects_Completed          int64
Placement                     str
dtype: object

In [15]:
df["Placement"].value_counts()

Placement
No     8341
Yes    1659
Name: count, dtype: int64

In [16]:
df["Internship_Experience"].value_counts()

Internship_Experience
No     6036
Yes    3964
Name: count, dtype: int64

In [17]:
df["CGPA"].min(), df["CGPA"].max()

(np.float64(4.54), np.float64(10.46))

In [18]:
df[df["CGPA"] > 10]

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
17,CLG0050,104,9.61,10.01,10,Yes,9,2,4,No
119,CLG0058,111,9.92,10.37,1,No,4,5,1,No
127,CLG0057,91,9.76,10.17,2,No,2,8,0,No
178,CLG0056,96,9.72,10.07,7,No,9,5,2,No
206,CLG0040,107,9.79,10.02,9,No,4,6,5,No
...,...,...,...,...,...,...,...,...,...,...
9903,CLG0051,99,9.92,10.28,6,No,10,9,5,Yes
9933,CLG0037,89,9.98,10.05,9,Yes,8,1,0,No
9953,CLG0069,85,9.70,10.02,9,No,2,4,2,No
9964,CLG0090,123,9.93,10.01,6,No,0,4,5,Yes
9992,CLG0062,109,9.92,10.09,2,Yes,5,10,3,Yes

In [19]:
df["Academic_Performance"].min(), df["Academic_Performance"].max()

(np.int64(1), np.int64(10))

In [20]:
df["Prev_Sem_Result"].min(), df["Prev_Sem_Result"].max()

(np.float64(5.0), np.float64(10.0))

In [21]:
(df["CGPA"] > 10).sum()

np.int64(249)

In [22]:
(df["CGPA"] < 0).sum()

np.int64(0)

In [23]:
(df["IQ"] < 0).sum()

np.int64(0)

In [24]:
placement_rate = (df["Placement"].value_counts()["Yes"] / len(df)) * 100
placement_rate

np.float64(16.59)

In [25]:
df.groupby("Internship_Experience")["Placement"].value_counts(normalize=True) * 100

Internship_Experience  Placement
No                     No           83.233930
                       Yes          16.766070
Yes                    No           83.678103
                       Yes          16.321897
Name: proportion, dtype: float64

In [26]:
pd.crosstab(
    df["Internship_Experience"],
    df["Placement"],
    normalize="index"
) * 100

Placement                     No        Yes
Internship_Experience
No                     83.233930  16.766070
Yes                    83.678103  16.321897

In [27]:
df.groupby("Placement")["CGPA"].mean()

Placement
No     7.321527
Yes    8.592483
Name: CGPA, dtype: float64

In [28]:
df.groupby("Academic_Performance")["Placement"].value_counts(normalize=True) * 100

Academic_Performance  Placement
1                     No           82.346833
                      Yes          17.653167
2                     No           83.216080
                      Yes          16.783920
3                     No           82.341070
                      Yes          17.658930
4                     No           81.274900
                      Yes          18.725100
5                     No           83.880903
                      Yes          16.119097
6                     No           85.151515
                      Yes          14.848485
7                     No           85.491723
                      Yes          14.508277
8                     No           83.121951
                      Yes          16.878049
9                     No           83.485309
                      Yes          16.514691
10                    No           83.716475
                      Yes          16.283525
Name: proportion, dtype: float64

In [29]:
df.groupby("Placement")["Prev_Sem_Result"].mean()

Placement
No     7.330462
Yes    8.567420
Name: Prev_Sem_Result, dtype: float64

In [30]:
df.groupby("Projects_Completed")["Placement"].value_counts(normalize=True) * 100

Projects_Completed  Placement
0                   No           97.334123
                    Yes           2.665877
1                   No           97.949037
                    Yes           2.050963
2                   No           75.788221
                    Yes          24.211779
3                   No           76.090965
                    Yes          23.909035
4                   No           77.495570
                    Yes          22.504430
5                   No           76.263220
                    Yes          23.736780
Name: proportion, dtype: float64